// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: app/log/config.proto

package log

import (
	log "github.com/xtls/xray-core/common/log"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogType int32

const (
	LogType_None    LogType = 0
	LogType_Console LogType = 1
	LogType_File    LogType = 2
	LogType_Event   LogType = 3
)

// Enum value maps for LogType.
var (
	LogType_name = map[int32]string{
		0: "None",
		1: "Console",
		2: "File",
		3: "Event",
	}
	LogType_value = map[string]int32{
		"None":    0,
		"Console": 1,
		"File":    2,
		"Event":   3,
	}
)

func (x LogType) Enum() *LogType {
	p := new(LogType)
	*p = x
	return p
}

func (x LogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_log_config_proto_enumTypes[0].Descriptor()
}

func (LogType) Type() protoreflect.EnumType {
	return &file_app_log_config_proto_enumTypes[0]
}

func (x LogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogType.Descriptor instead.
func (LogType) EnumDescriptor() ([]byte, []int) {
	return file_app_log_config_proto_rawDescGZIP(), []int{0}
}

type OutputType int32

const (
	OutputType_OutputUnknown OutputType = 0
	OutputType_OutputConsole OutputType = 1
	OutputType_OutputFile    OutputType = 2
	OutputType_OutputUnix    OutputType = 3
)

// Enum value maps for OutputType.
var (
	OutputType_name = map[int32]string{
		0: "OutputUnknown",
		1: "OutputConsole",
		2: "OutputFile",
		3: "OutputUnix",
	}
	OutputType_value = map[string]int32{
		"OutputUnknown": 0,
		"OutputConsole": 1,
		"OutputFile":    2,
		"OutputUnix":    3,
	}
)

func (x OutputType) Enum() *OutputType {
	p := new(OutputType)
	*p = x
	return p
}

func (x OutputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_log_config_proto_enumTypes[1].Descriptor()
}

func (OutputType) Type() protoreflect.EnumType {
	return &file_app_log_config_proto_enumTypes[1]
}

func (x OutputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputType.Descriptor instead.
func (OutputType) EnumDescriptor() ([]byte, []int) {
	return file_app_log_config_proto_rawDescGZIP(), []int{1}
}

type LogFormat int32

const (
	LogFormat_FormatUnknown LogFormat = 0
	LogFormat_FormatConsole LogFormat = 1
	LogFormat_FormatJSON    LogFormat = 2
	LogFormat_FormatLegacy  LogFormat = 3
)

// Enum value maps for LogFormat.
var (
	LogFormat_name = map[int32]string{
		0: "FormatUnknown",
		1: "FormatConsole",
		2: "FormatJSON",
		3: "FormatLegacy",
	}
	LogFormat_value = map[string]int32{
		"FormatUnknown": 0,
		"FormatConsole": 1,
		"FormatJSON":    2,
		"FormatLegacy":  3,
	}
)

func (x LogFormat) Enum() *LogFormat {
	p := new(LogFormat)
	*p = x
	return p
}

func (x LogFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_app_log_config_proto_enumTypes[2].Descriptor()
}

func (LogFormat) Type() protoreflect.EnumType {
	return &file_app_log_config_proto_enumTypes[2]
}

func (x LogFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogFormat.Descriptor instead.
func (LogFormat) EnumDescriptor() ([]byte, []int) {
	return file_app_log_config_proto_rawDescGZIP(), []int{2}
}

type ColorMode int32

const (
	ColorMode_ColorAuto   ColorMode = 0
	ColorMode_ColorAlways ColorMode = 1
	ColorMode_ColorNever  ColorMode = 2
)

// Enum value maps for ColorMode.
var (
	ColorMode_name = map[int32]string{
		0: "ColorAuto",
		1: "ColorAlways",
		2: "ColorNever",
	}
	ColorMode_value = map[string]int32{
		"ColorAuto":   0,
		"ColorAlways": 1,
		"ColorNever":  2,
	}
)

func (x ColorMode) Enum() *ColorMode {
	p := new(ColorMode)
	*p = x
	return p
}

func (x ColorMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColorMode) Descriptor() protoreflect.EnumDescriptor {
	return file_app_log_config_proto_enumTypes[3].Descriptor()
}

func (ColorMode) Type() protoreflect.EnumType {
	return &file_app_log_config_proto_enumTypes[3]
}

func (x ColorMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColorMode.Descriptor instead.
func (ColorMode) EnumDescriptor() ([]byte, []int) {
	return file_app_log_config_proto_rawDescGZIP(), []int{3}
}

type Backpressure int32

const (
	Backpressure_BackpressureDropNew Backpressure = 0
	Backpressure_BackpressureBlock   Backpressure = 1
	Backpressure_BackpressureSync    Backpressure = 2
)

// Enum value maps for Backpressure.
var (
	Backpressure_name = map[int32]string{
		0: "BackpressureDropNew",
		1: "BackpressureBlock",
		2: "BackpressureSync",
	}
	Backpressure_value = map[string]int32{
		"BackpressureDropNew": 0,
		"BackpressureBlock":   1,
		"BackpressureSync":    2,
	}
)

func (x Backpressure) Enum() *Backpressure {
	p := new(Backpressure)
	*p = x
	return p
}

func (x Backpressure) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Backpressure) Descriptor() protoreflect.EnumDescriptor {
	return file_app_log_config_proto_enumTypes[4].Descriptor()
}

func (Backpressure) Type() protoreflect.EnumType {
	return &file_app_log_config_proto_enumTypes[4]
}

func (x Backpressure) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Backpressure.Descriptor instead.
func (Backpressure) EnumDescriptor() ([]byte, []int) {
	return file_app_log_config_proto_rawDescGZIP(), []int{4}
}

type EventType int32

const (
	EventType_EventGeneral  EventType = 0
	EventType_EventAccess   EventType = 1
	EventType_EventDNS      EventType = 2
	EventType_EventInternal EventType = 3
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EventGeneral",
		1: "EventAccess",
		2: "EventDNS",
		3: "EventInternal",
	}
	EventType_value = map[string]int32{
		"EventGeneral":  0,
		"EventAccess":   1,
		"EventDNS":      2,
		"EventInternal": 3,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_log_config_proto_enumTypes[5].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_app_log_config_proto_enumTypes[5]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_app_log_config_proto_rawDescGZIP(), []int{5}
}

type ConsoleStream int32

const (
	ConsoleStream_StreamStdout ConsoleStream = 0
	ConsoleStream_StreamStderr ConsoleStream = 1
)

// Enum value maps for ConsoleStream.
var (
	ConsoleStream_name = map[int32]string{
		0: "StreamStdout",
		1: "StreamStderr",
	}
	ConsoleStream_value = map[string]int32{
		"StreamStdout": 0,
		"StreamStderr": 1,
	}
)

func (x ConsoleStream) Enum() *ConsoleStream {
	p := new(ConsoleStream)
	*p = x
	return p
}

func (x ConsoleStream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsoleStream) Descriptor() protoreflect.EnumDescriptor {
	return file_app_log_config_proto_enumTypes[6].Descriptor()
}

func (ConsoleStream) Type() protoreflect.EnumType {
	return &file_app_log_config_proto_enumTypes[6]
}

func (x ConsoleStream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsoleStream.Descriptor instead.
func (ConsoleStream) EnumDescriptor() ([]byte, []int) {
	return file_app_log_config_proto_rawDescGZIP(), []int{6}
}

type OutputConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type           OutputType             `protobuf:"varint,2,opt,name=type,proto3,enum=xray.app.log.OutputType" json:"type,omitempty"`
	Path           string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Stream         ConsoleStream          `protobuf:"varint,4,opt,name=stream,proto3,enum=xray.app.log.ConsoleStream" json:"stream,omitempty"`
	Format         LogFormat              `protobuf:"varint,5,opt,name=format,proto3,enum=xray.app.log.LogFormat" json:"format,omitempty"`
	Color          ColorMode              `protobuf:"varint,6,opt,name=color,proto3,enum=xray.app.log.ColorMode" json:"color,omitempty"`
	Events         []EventType            `protobuf:"varint,7,rep,packed,name=events,proto3,enum=xray.app.log.EventType" json:"events,omitempty"`
	Level          log.Severity           `protobuf:"varint,8,opt,name=level,proto3,enum=xray.common.log.Severity" json:"level,omitempty"`
	QueueSize      uint32                 `protobuf:"varint,9,opt,name=queue_size,json=queueSize,proto3" json:"queue_size,omitempty"`
	BatchSize      uint32                 `protobuf:"varint,10,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	FlushInterval  int64                  `protobuf:"varint,11,opt,name=flush_interval,json=flushInterval,proto3" json:"flush_interval,omitempty"`
	Backpressure   Backpressure           `protobuf:"varint,12,opt,name=backpressure,proto3,enum=xray.app.log.Backpressure" json:"backpressure,omitempty"`
	BlockTimeout   int64                  `protobuf:"varint,13,opt,name=block_timeout,json=blockTimeout,proto3" json:"block_timeout,omitempty"`
	MaxRecordSize  uint32                 `protobuf:"varint,14,opt,name=max_record_size,json=maxRecordSize,proto3" json:"max_record_size,omitempty"`
	FileBufferSize uint32                 `protobuf:"varint,15,opt,name=file_buffer_size,json=fileBufferSize,proto3" json:"file_buffer_size,omitempty"`
	ConnectTimeout int64                  `protobuf:"varint,16,opt,name=connect_timeout,json=connectTimeout,proto3" json:"connect_timeout,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OutputConfig) Reset() {
	*x = OutputConfig{}
	mi := &file_app_log_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputConfig) ProtoMessage() {}

func (x *OutputConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_log_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputConfig.ProtoReflect.Descriptor instead.
func (*OutputConfig) Descriptor() ([]byte, []int) {
	return file_app_log_config_proto_rawDescGZIP(), []int{0}
}

func (x *OutputConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OutputConfig) GetType() OutputType {
	if x != nil {
		return x.Type
	}
	return OutputType_OutputUnknown
}

func (x *OutputConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *OutputConfig) GetStream() ConsoleStream {
	if x != nil {
		return x.Stream
	}
	return ConsoleStream_StreamStdout
}

func (x *OutputConfig) GetFormat() LogFormat {
	if x != nil {
		return x.Format
	}
	return LogFormat_FormatUnknown
}

func (x *OutputConfig) GetColor() ColorMode {
	if x != nil {
		return x.Color
	}
	return ColorMode_ColorAuto
}

func (x *OutputConfig) GetEvents() []EventType {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *OutputConfig) GetLevel() log.Severity {
	if x != nil {
		return x.Level
	}
	return log.Severity(0)
}

func (x *OutputConfig) GetQueueSize() uint32 {
	if x != nil {
		return x.QueueSize
	}
	return 0
}

func (x *OutputConfig) GetBatchSize() uint32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *OutputConfig) GetFlushInterval() int64 {
	if x != nil {
		return x.FlushInterval
	}
	return 0
}

func (x *OutputConfig) GetBackpressure() Backpressure {
	if x != nil {
		return x.Backpressure
	}
	return Backpressure_BackpressureDropNew
}

func (x *OutputConfig) GetBlockTimeout() int64 {
	if x != nil {
		return x.BlockTimeout
	}
	return 0
}

func (x *OutputConfig) GetMaxRecordSize() uint32 {
	if x != nil {
		return x.MaxRecordSize
	}
	return 0
}

func (x *OutputConfig) GetFileBufferSize() uint32 {
	if x != nil {
		return x.FileBufferSize
	}
	return 0
}

func (x *OutputConfig) GetConnectTimeout() int64 {
	if x != nil {
		return x.ConnectTimeout
	}
	return 0
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorLogType  LogType                `protobuf:"varint,1,opt,name=error_log_type,json=errorLogType,proto3,enum=xray.app.log.LogType" json:"error_log_type,omitempty"`
	ErrorLogLevel log.Severity           `protobuf:"varint,2,opt,name=error_log_level,json=errorLogLevel,proto3,enum=xray.common.log.Severity" json:"error_log_level,omitempty"`
	ErrorLogPath  string                 `protobuf:"bytes,3,opt,name=error_log_path,json=errorLogPath,proto3" json:"error_log_path,omitempty"`
	AccessLogType LogType                `protobuf:"varint,4,opt,name=access_log_type,json=accessLogType,proto3,enum=xray.app.log.LogType" json:"access_log_type,omitempty"`
	AccessLogPath string                 `protobuf:"bytes,5,opt,name=access_log_path,json=accessLogPath,proto3" json:"access_log_path,omitempty"`
	EnableDnsLog  bool                   `protobuf:"varint,6,opt,name=enable_dns_log,json=enableDnsLog,proto3" json:"enable_dns_log,omitempty"`
	MaskAddress   string                 `protobuf:"bytes,7,opt,name=mask_address,json=maskAddress,proto3" json:"mask_address,omitempty"`
	Outputs       []*OutputConfig        `protobuf:"bytes,8,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_log_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_log_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_log_config_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetErrorLogType() LogType {
	if x != nil {
		return x.ErrorLogType
	}
	return LogType_None
}

func (x *Config) GetErrorLogLevel() log.Severity {
	if x != nil {
		return x.ErrorLogLevel
	}
	return log.Severity(0)
}

func (x *Config) GetErrorLogPath() string {
	if x != nil {
		return x.ErrorLogPath
	}
	return ""
}

func (x *Config) GetAccessLogType() LogType {
	if x != nil {
		return x.AccessLogType
	}
	return LogType_None
}

func (x *Config) GetAccessLogPath() string {
	if x != nil {
		return x.AccessLogPath
	}
	return ""
}

func (x *Config) GetEnableDnsLog() bool {
	if x != nil {
		return x.EnableDnsLog
	}
	return false
}

func (x *Config) GetMaskAddress() string {
	if x != nil {
		return x.MaskAddress
	}
	return ""
}

func (x *Config) GetOutputs() []*OutputConfig {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_app_log_config_proto protoreflect.FileDescriptor

const file_app_log_config_proto_rawDesc = "" +
	"\n" +
	"\x14app/log/config.proto\x12\fxray.app.log\x1a\x14common/log/log.proto\"\xa0\x05\n" +
	"\fOutputConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.xray.app.log.OutputTypeR\x04type\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x123\n" +
	"\x06stream\x18\x04 \x01(\x0e2\x1b.xray.app.log.ConsoleStreamR\x06stream\x12/\n" +
	"\x06format\x18\x05 \x01(\x0e2\x17.xray.app.log.LogFormatR\x06format\x12-\n" +
	"\x05color\x18\x06 \x01(\x0e2\x17.xray.app.log.ColorModeR\x05color\x12/\n" +
	"\x06events\x18\a \x03(\x0e2\x17.xray.app.log.EventTypeR\x06events\x12/\n" +
	"\x05level\x18\b \x01(\x0e2\x19.xray.common.log.SeverityR\x05level\x12\x1d\n" +
	"\n" +
	"queue_size\x18\t \x01(\rR\tqueueSize\x12\x1d\n" +
	"\n" +
	"batch_size\x18\n" +
	" \x01(\rR\tbatchSize\x12%\n" +
	"\x0eflush_interval\x18\v \x01(\x03R\rflushInterval\x12>\n" +
	"\fbackpressure\x18\f \x01(\x0e2\x1a.xray.app.log.BackpressureR\fbackpressure\x12#\n" +
	"\rblock_timeout\x18\r \x01(\x03R\fblockTimeout\x12&\n" +
	"\x0fmax_record_size\x18\x0e \x01(\rR\rmaxRecordSize\x12(\n" +
	"\x10file_buffer_size\x18\x0f \x01(\rR\x0efileBufferSize\x12'\n" +
	"\x0fconnect_timeout\x18\x10 \x01(\x03R\x0econnectTimeout\"\x94\x03\n" +
	"\x06Config\x12;\n" +
	"\x0eerror_log_type\x18\x01 \x01(\x0e2\x15.xray.app.log.LogTypeR\ferrorLogType\x12A\n" +
	"\x0ferror_log_level\x18\x02 \x01(\x0e2\x19.xray.common.log.SeverityR\rerrorLogLevel\x12$\n" +
	"\x0eerror_log_path\x18\x03 \x01(\tR\ferrorLogPath\x12=\n" +
	"\x0faccess_log_type\x18\x04 \x01(\x0e2\x15.xray.app.log.LogTypeR\raccessLogType\x12&\n" +
	"\x0faccess_log_path\x18\x05 \x01(\tR\raccessLogPath\x12$\n" +
	"\x0eenable_dns_log\x18\x06 \x01(\bR\fenableDnsLog\x12!\n" +
	"\fmask_address\x18\a \x01(\tR\vmaskAddress\x124\n" +
	"\aoutputs\x18\b \x03(\v2\x1a.xray.app.log.OutputConfigR\aoutputs*5\n" +
	"\aLogType\x12\b\n" +
	"\x04None\x10\x00\x12\v\n" +
	"\aConsole\x10\x01\x12\b\n" +
	"\x04File\x10\x02\x12\t\n" +
	"\x05Event\x10\x03*R\n" +
	"\n" +
	"OutputType\x12\x11\n" +
	"\rOutputUnknown\x10\x00\x12\x11\n" +
	"\rOutputConsole\x10\x01\x12\x0e\n" +
	"\n" +
	"OutputFile\x10\x02\x12\x0e\n" +
	"\n" +
	"OutputUnix\x10\x03*S\n" +
	"\tLogFormat\x12\x11\n" +
	"\rFormatUnknown\x10\x00\x12\x11\n" +
	"\rFormatConsole\x10\x01\x12\x0e\n" +
	"\n" +
	"FormatJSON\x10\x02\x12\x10\n" +
	"\fFormatLegacy\x10\x03*;\n" +
	"\tColorMode\x12\r\n" +
	"\tColorAuto\x10\x00\x12\x0f\n" +
	"\vColorAlways\x10\x01\x12\x0e\n" +
	"\n" +
	"ColorNever\x10\x02*T\n" +
	"\fBackpressure\x12\x17\n" +
	"\x13BackpressureDropNew\x10\x00\x12\x15\n" +
	"\x11BackpressureBlock\x10\x01\x12\x14\n" +
	"\x10BackpressureSync\x10\x02*O\n" +
	"\tEventType\x12\x10\n" +
	"\fEventGeneral\x10\x00\x12\x0f\n" +
	"\vEventAccess\x10\x01\x12\f\n" +
	"\bEventDNS\x10\x02\x12\x11\n" +
	"\rEventInternal\x10\x03*3\n" +
	"\rConsoleStream\x12\x10\n" +
	"\fStreamStdout\x10\x00\x12\x10\n" +
	"\fStreamStderr\x10\x01BF\n" +
	"\x10com.xray.app.logP\x01Z!github.com/xtls/xray-core/app/log\xaa\x02\fXray.App.Logb\x06proto3"

var (
	file_app_log_config_proto_rawDescOnce sync.Once
	file_app_log_config_proto_rawDescData []byte
)

func file_app_log_config_proto_rawDescGZIP() []byte {
	file_app_log_config_proto_rawDescOnce.Do(func() {
		file_app_log_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_log_config_proto_rawDesc), len(file_app_log_config_proto_rawDesc)))
	})
	return file_app_log_config_proto_rawDescData
}

var file_app_log_config_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_app_log_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_log_config_proto_goTypes = []any{
	(LogType)(0),         // 0: xray.app.log.LogType
	(OutputType)(0),      // 1: xray.app.log.OutputType
	(LogFormat)(0),       // 2: xray.app.log.LogFormat
	(ColorMode)(0),       // 3: xray.app.log.ColorMode
	(Backpressure)(0),    // 4: xray.app.log.Backpressure
	(EventType)(0),       // 5: xray.app.log.EventType
	(ConsoleStream)(0),   // 6: xray.app.log.ConsoleStream
	(*OutputConfig)(nil), // 7: xray.app.log.OutputConfig
	(*Config)(nil),       // 8: xray.app.log.Config
	(log.Severity)(0),    // 9: xray.common.log.Severity
}
var file_app_log_config_proto_depIdxs = []int32{
	1,  // 0: xray.app.log.OutputConfig.type:type_name -> xray.app.log.OutputType
	6,  // 1: xray.app.log.OutputConfig.stream:type_name -> xray.app.log.ConsoleStream
	2,  // 2: xray.app.log.OutputConfig.format:type_name -> xray.app.log.LogFormat
	3,  // 3: xray.app.log.OutputConfig.color:type_name -> xray.app.log.ColorMode
	5,  // 4: xray.app.log.OutputConfig.events:type_name -> xray.app.log.EventType
	9,  // 5: xray.app.log.OutputConfig.level:type_name -> xray.common.log.Severity
	4,  // 6: xray.app.log.OutputConfig.backpressure:type_name -> xray.app.log.Backpressure
	0,  // 7: xray.app.log.Config.error_log_type:type_name -> xray.app.log.LogType
	9,  // 8: xray.app.log.Config.error_log_level:type_name -> xray.common.log.Severity
	0,  // 9: xray.app.log.Config.access_log_type:type_name -> xray.app.log.LogType
	7,  // 10: xray.app.log.Config.outputs:type_name -> xray.app.log.OutputConfig
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_app_log_config_proto_init() }
func file_app_log_config_proto_init() {
	if File_app_log_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_log_config_proto_rawDesc), len(file_app_log_config_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_log_config_proto_goTypes,
		DependencyIndexes: file_app_log_config_proto_depIdxs,
		EnumInfos:         file_app_log_config_proto_enumTypes,
		MessageInfos:      file_app_log_config_proto_msgTypes,
	}.Build()
	File_app_log_config_proto = out.File
	file_app_log_config_proto_goTypes = nil
	file_app_log_config_proto_depIdxs = nil
}
