// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proxy/mtproxy/config.proto

package mtproxy

import (
	protocol "github.com/xtls/xray-core/common/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpstreamSource int32

const (
	UpstreamSource_UPSTREAM_SOURCE_UNSPECIFIED UpstreamSource = 0
	UpstreamSource_UPSTREAM_SOURCE_FILES       UpstreamSource = 1
	UpstreamSource_UPSTREAM_SOURCE_TELEGRAM    UpstreamSource = 2
)

// Enum value maps for UpstreamSource.
var (
	UpstreamSource_name = map[int32]string{
		0: "UPSTREAM_SOURCE_UNSPECIFIED",
		1: "UPSTREAM_SOURCE_FILES",
		2: "UPSTREAM_SOURCE_TELEGRAM",
	}
	UpstreamSource_value = map[string]int32{
		"UPSTREAM_SOURCE_UNSPECIFIED": 0,
		"UPSTREAM_SOURCE_FILES":       1,
		"UPSTREAM_SOURCE_TELEGRAM":    2,
	}
)

func (x UpstreamSource) Enum() *UpstreamSource {
	p := new(UpstreamSource)
	*p = x
	return p
}

func (x UpstreamSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpstreamSource) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_mtproxy_config_proto_enumTypes[0].Descriptor()
}

func (UpstreamSource) Type() protoreflect.EnumType {
	return &file_proxy_mtproxy_config_proto_enumTypes[0]
}

func (x UpstreamSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpstreamSource.Descriptor instead.
func (UpstreamSource) EnumDescriptor() ([]byte, []int) {
	return file_proxy_mtproxy_config_proto_rawDescGZIP(), []int{0}
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        []byte                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proxy_mtproxy_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_mtproxy_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proxy_mtproxy_config_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

type UpstreamConfig struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Source                 UpstreamSource         `protobuf:"varint,1,opt,name=source,proto3,enum=xray.proxy.mtproxy.UpstreamSource" json:"source,omitempty"`
	SecretFile             string                 `protobuf:"bytes,2,opt,name=secret_file,json=secretFile,proto3" json:"secret_file,omitempty"`
	ConfigFile             string                 `protobuf:"bytes,3,opt,name=config_file,json=configFile,proto3" json:"config_file,omitempty"`
	CacheDir               string                 `protobuf:"bytes,4,opt,name=cache_dir,json=cacheDir,proto3" json:"cache_dir,omitempty"`
	RefreshIntervalSeconds uint32                 `protobuf:"varint,5,opt,name=refresh_interval_seconds,json=refreshIntervalSeconds,proto3" json:"refresh_interval_seconds,omitempty"`
	ProxyTag               []byte                 `protobuf:"bytes,6,opt,name=proxy_tag,json=proxyTag,proto3" json:"proxy_tag,omitempty"`
	MaxSessionsPerDc       uint32                 `protobuf:"varint,7,opt,name=max_sessions_per_dc,json=maxSessionsPerDc,proto3" json:"max_sessions_per_dc,omitempty"`
	MaxClientsPerSession   uint32                 `protobuf:"varint,8,opt,name=max_clients_per_session,json=maxClientsPerSession,proto3" json:"max_clients_per_session,omitempty"`
	DeliveryQueueDepth     uint32                 `protobuf:"varint,9,opt,name=delivery_queue_depth,json=deliveryQueueDepth,proto3" json:"delivery_queue_depth,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpstreamConfig) Reset() {
	*x = UpstreamConfig{}
	mi := &file_proxy_mtproxy_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamConfig) ProtoMessage() {}

func (x *UpstreamConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_mtproxy_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamConfig.ProtoReflect.Descriptor instead.
func (*UpstreamConfig) Descriptor() ([]byte, []int) {
	return file_proxy_mtproxy_config_proto_rawDescGZIP(), []int{1}
}

func (x *UpstreamConfig) GetSource() UpstreamSource {
	if x != nil {
		return x.Source
	}
	return UpstreamSource_UPSTREAM_SOURCE_UNSPECIFIED
}

func (x *UpstreamConfig) GetSecretFile() string {
	if x != nil {
		return x.SecretFile
	}
	return ""
}

func (x *UpstreamConfig) GetConfigFile() string {
	if x != nil {
		return x.ConfigFile
	}
	return ""
}

func (x *UpstreamConfig) GetCacheDir() string {
	if x != nil {
		return x.CacheDir
	}
	return ""
}

func (x *UpstreamConfig) GetRefreshIntervalSeconds() uint32 {
	if x != nil {
		return x.RefreshIntervalSeconds
	}
	return 0
}

func (x *UpstreamConfig) GetProxyTag() []byte {
	if x != nil {
		return x.ProxyTag
	}
	return nil
}

func (x *UpstreamConfig) GetMaxSessionsPerDc() uint32 {
	if x != nil {
		return x.MaxSessionsPerDc
	}
	return 0
}

func (x *UpstreamConfig) GetMaxClientsPerSession() uint32 {
	if x != nil {
		return x.MaxClientsPerSession
	}
	return 0
}

func (x *UpstreamConfig) GetDeliveryQueueDepth() uint32 {
	if x != nil {
		return x.DeliveryQueueDepth
	}
	return 0
}

type FakeTLSConfig struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Enabled                bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Only                   bool                   `protobuf:"varint,2,opt,name=only,proto3" json:"only,omitempty"`
	Domains                []string               `protobuf:"bytes,3,rep,name=domains,proto3" json:"domains,omitempty"`
	ReplayCacheCapacity    uint32                 `protobuf:"varint,4,opt,name=replay_cache_capacity,json=replayCacheCapacity,proto3" json:"replay_cache_capacity,omitempty"`
	ServerHelloPayloadSize uint32                 `protobuf:"varint,5,opt,name=server_hello_payload_size,json=serverHelloPayloadSize,proto3" json:"server_hello_payload_size,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FakeTLSConfig) Reset() {
	*x = FakeTLSConfig{}
	mi := &file_proxy_mtproxy_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FakeTLSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FakeTLSConfig) ProtoMessage() {}

func (x *FakeTLSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_mtproxy_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FakeTLSConfig.ProtoReflect.Descriptor instead.
func (*FakeTLSConfig) Descriptor() ([]byte, []int) {
	return file_proxy_mtproxy_config_proto_rawDescGZIP(), []int{2}
}

func (x *FakeTLSConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FakeTLSConfig) GetOnly() bool {
	if x != nil {
		return x.Only
	}
	return false
}

func (x *FakeTLSConfig) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *FakeTLSConfig) GetReplayCacheCapacity() uint32 {
	if x != nil {
		return x.ReplayCacheCapacity
	}
	return 0
}

func (x *FakeTLSConfig) GetServerHelloPayloadSize() uint32 {
	if x != nil {
		return x.ServerHelloPayloadSize
	}
	return 0
}

type Config struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Users                []*protocol.User       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Upstream             *UpstreamConfig        `protobuf:"bytes,2,opt,name=upstream,proto3" json:"upstream,omitempty"`
	FakeTls              *FakeTLSConfig         `protobuf:"bytes,3,opt,name=fake_tls,json=fakeTls,proto3" json:"fake_tls,omitempty"`
	MaxSecrets           uint32                 `protobuf:"varint,4,opt,name=max_secrets,json=maxSecrets,proto3" json:"max_secrets,omitempty"`
	MaxPacketSize        uint32                 `protobuf:"varint,5,opt,name=max_packet_size,json=maxPacketSize,proto3" json:"max_packet_size,omitempty"`
	HandshakeConcurrency uint32                 `protobuf:"varint,6,opt,name=handshake_concurrency,json=handshakeConcurrency,proto3" json:"handshake_concurrency,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_proxy_mtproxy_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_mtproxy_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_proxy_mtproxy_config_proto_rawDescGZIP(), []int{3}
}

func (x *Config) GetUsers() []*protocol.User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Config) GetUpstream() *UpstreamConfig {
	if x != nil {
		return x.Upstream
	}
	return nil
}

func (x *Config) GetFakeTls() *FakeTLSConfig {
	if x != nil {
		return x.FakeTls
	}
	return nil
}

func (x *Config) GetMaxSecrets() uint32 {
	if x != nil {
		return x.MaxSecrets
	}
	return 0
}

func (x *Config) GetMaxPacketSize() uint32 {
	if x != nil {
		return x.MaxPacketSize
	}
	return 0
}

func (x *Config) GetHandshakeConcurrency() uint32 {
	if x != nil {
		return x.HandshakeConcurrency
	}
	return 0
}

var File_proxy_mtproxy_config_proto protoreflect.FileDescriptor

const file_proxy_mtproxy_config_proto_rawDesc = "" +
	"\n" +
	"\x1aproxy/mtproxy/config.proto\x12\x12xray.proxy.mtproxy\x1a\x1acommon/protocol/user.proto\"!\n" +
	"\aAccount\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\fR\x06secret\"\x9a\x03\n" +
	"\x0eUpstreamConfig\x12:\n" +
	"\x06source\x18\x01 \x01(\x0e2\".xray.proxy.mtproxy.UpstreamSourceR\x06source\x12\x1f\n" +
	"\vsecret_file\x18\x02 \x01(\tR\n" +
	"secretFile\x12\x1f\n" +
	"\vconfig_file\x18\x03 \x01(\tR\n" +
	"configFile\x12\x1b\n" +
	"\tcache_dir\x18\x04 \x01(\tR\bcacheDir\x128\n" +
	"\x18refresh_interval_seconds\x18\x05 \x01(\rR\x16refreshIntervalSeconds\x12\x1b\n" +
	"\tproxy_tag\x18\x06 \x01(\fR\bproxyTag\x12-\n" +
	"\x13max_sessions_per_dc\x18\a \x01(\rR\x10maxSessionsPerDc\x125\n" +
	"\x17max_clients_per_session\x18\b \x01(\rR\x14maxClientsPerSession\x120\n" +
	"\x14delivery_queue_depth\x18\t \x01(\rR\x12deliveryQueueDepth\"\xc6\x01\n" +
	"\rFakeTLSConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04only\x18\x02 \x01(\bR\x04only\x12\x18\n" +
	"\adomains\x18\x03 \x03(\tR\adomains\x122\n" +
	"\x15replay_cache_capacity\x18\x04 \x01(\rR\x13replayCacheCapacity\x129\n" +
	"\x19server_hello_payload_size\x18\x05 \x01(\rR\x16serverHelloPayloadSize\"\xb6\x02\n" +
	"\x06Config\x120\n" +
	"\x05users\x18\x01 \x03(\v2\x1a.xray.common.protocol.UserR\x05users\x12>\n" +
	"\bupstream\x18\x02 \x01(\v2\".xray.proxy.mtproxy.UpstreamConfigR\bupstream\x12<\n" +
	"\bfake_tls\x18\x03 \x01(\v2!.xray.proxy.mtproxy.FakeTLSConfigR\afakeTls\x12\x1f\n" +
	"\vmax_secrets\x18\x04 \x01(\rR\n" +
	"maxSecrets\x12&\n" +
	"\x0fmax_packet_size\x18\x05 \x01(\rR\rmaxPacketSize\x123\n" +
	"\x15handshake_concurrency\x18\x06 \x01(\rR\x14handshakeConcurrency*j\n" +
	"\x0eUpstreamSource\x12\x1f\n" +
	"\x1bUPSTREAM_SOURCE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15UPSTREAM_SOURCE_FILES\x10\x01\x12\x1c\n" +
	"\x18UPSTREAM_SOURCE_TELEGRAM\x10\x02BX\n" +
	"\x16com.xray.proxy.mtproxyP\x01Z'github.com/xtls/xray-core/proxy/mtproxy\xaa\x02\x12Xray.Proxy.MTProxyb\x06proto3"

var (
	file_proxy_mtproxy_config_proto_rawDescOnce sync.Once
	file_proxy_mtproxy_config_proto_rawDescData []byte
)

func file_proxy_mtproxy_config_proto_rawDescGZIP() []byte {
	file_proxy_mtproxy_config_proto_rawDescOnce.Do(func() {
		file_proxy_mtproxy_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_mtproxy_config_proto_rawDesc), len(file_proxy_mtproxy_config_proto_rawDesc)))
	})
	return file_proxy_mtproxy_config_proto_rawDescData
}

var file_proxy_mtproxy_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proxy_mtproxy_config_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proxy_mtproxy_config_proto_goTypes = []any{
	(UpstreamSource)(0),    // 0: xray.proxy.mtproxy.UpstreamSource
	(*Account)(nil),        // 1: xray.proxy.mtproxy.Account
	(*UpstreamConfig)(nil), // 2: xray.proxy.mtproxy.UpstreamConfig
	(*FakeTLSConfig)(nil),  // 3: xray.proxy.mtproxy.FakeTLSConfig
	(*Config)(nil),         // 4: xray.proxy.mtproxy.Config
	(*protocol.User)(nil),  // 5: xray.common.protocol.User
}
var file_proxy_mtproxy_config_proto_depIdxs = []int32{
	0, // 0: xray.proxy.mtproxy.UpstreamConfig.source:type_name -> xray.proxy.mtproxy.UpstreamSource
	5, // 1: xray.proxy.mtproxy.Config.users:type_name -> xray.common.protocol.User
	2, // 2: xray.proxy.mtproxy.Config.upstream:type_name -> xray.proxy.mtproxy.UpstreamConfig
	3, // 3: xray.proxy.mtproxy.Config.fake_tls:type_name -> xray.proxy.mtproxy.FakeTLSConfig
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proxy_mtproxy_config_proto_init() }
func file_proxy_mtproxy_config_proto_init() {
	if File_proxy_mtproxy_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_mtproxy_config_proto_rawDesc), len(file_proxy_mtproxy_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_mtproxy_config_proto_goTypes,
		DependencyIndexes: file_proxy_mtproxy_config_proto_depIdxs,
		EnumInfos:         file_proxy_mtproxy_config_proto_enumTypes,
		MessageInfos:      file_proxy_mtproxy_config_proto_msgTypes,
	}.Build()
	File_proxy_mtproxy_config_proto = out.File
	file_proxy_mtproxy_config_proto_goTypes = nil
	file_proxy_mtproxy_config_proto_depIdxs = nil
}
